## should use the Linux newline character ##


[logs]
# LevelEmergency = iota
# LevelAlert
# LevelCritical
# LevelError
# LevelWarning
# LevelNotice
# LevelInformational
# LevelDebug
level=LevelDebug
#no extension, just name
name=mmap
dir=/root/rpki/rpstir2-mod/rpstir2-model/mmap/test/log/
async=false
# 1000MB
maxsize=1000
#if 0,will never delete
maxage=0
maxbackups=0
